### ISSUE TITLE
Ayeraco lose contact with one another upon Save/Restore NTB

### ISSUE THREAD

**Issue by krwminer** [NicosaurusRex99/DivineRPG#18]

**Comment by Oshi41** [comment]
Partial fix was at https://github.com/NicosaurusRex99/DivineRPG/commit/4782ec312088d3b93f3cfdb4d054833909215462

But beacons and summoning block are not rendering on multiplayer
Looks like we are sending the right packet about created tile entity but there are no tile entity to recieve it on client

`[22:07:00] [Client thread/ERROR] [minecraft/NetHandlerPlayClient]: Received invalid update packet for null tile entity at BlockPos{x=-16, y=65, z=3} with data: {texture:"divinerpg:textures/blocks/beam_red.png",x:-16,y:65,z:3,id:"divinerpg:te_ayeraco_beam"}`


StackTrace:
`Caused by: java.lang.NullPointerException
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:590) ~[Chunk.class:?]
	at net.minecraft.world.World.setBlockState(World.java:401) ~[World.class:?]
	at net.minecraft.client.multiplayer.WorldClient.invalidateRegionAndSetBlock(WorldClient.java:322) ~[WorldClient.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleBlockChange(NetHandlerPlayClient.java:853) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.processPacket(SPacketBlockChange.java:52) ~[SPacketBlockChange.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.processPacket(SPacketBlockChange.java:14) ~[SPacketBlockChange.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_222]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
`

**Comment by Oshi41** [comment]
Fixed summon item logic, code must executed on both sides.
I think I found forge problem
Block update package don't contains state (equals null)
Need to check with newest forge 2838 for now

**Comment by Oshi41** [comment]
Repeated still
It was because of both AyeracoBeam and Spawner was not registered

**Comment by Oshi41** [comment]
Fixed here https://github.com/NicosaurusRex99/DivineRPG/commit/4a293f4688c9424f00db546a4a00f6690c4fc7dc
But still have a render problem with nether or and ayeraco beams

![image](https://user-images.githubusercontent.com/29630406/63779519-562c6600-c8ef-11e9-9f22-235cdfc5f4fb.png)

**Comment by krwminer** [comment]
I think Netherite Ore is fixed, do you still have a problem with the Beams?

**Comment by Oshi41** [comment]
> I think Netherite Ore is fixed, do you still have a problem with the Beams?

The last one is AyeracoSpawner
![image](https://user-images.githubusercontent.com/29630406/63864894-4b3e0800-c9b9-11e9-9535-c2835fe1963f.png)
And that is all

**Comment by krwminer** [comment]
Fixed in https://github.com/NicosaurusRex99/DivineRPG/commit/e99a2baba1450b1a16294b4eff8c5f401394ad48
